apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    name: rest-api
spec:
  selector:
    matchLabels:
      name: rest-api 
  template:
    metadata:
      name: rest-api
      labels:
        name: rest-api
    spec:
      containers:
      - name: restapi-apps
        image: hkdock01/nodejs-restapi
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
spec:
  type: NodePort
  selector:
    name: rest-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
